version: '3.2'
services:

  spark-master:
    image: henricasanova/ics632_spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/spark
    networks:
      - spark-network

  spark-submit:
    image: henricasanova/ics632_spark-submit
    container_name: spark-submit
    volumes:
      - ./:/home/spark
    networks:
      - spark-network
    stdin_open: true
    tty: true

  spark-worker1:
    image: henricasanova/ics632_spark-worker
    container_name: spark-worker1
    depends_on: 
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./:/home/spark
    networks:
      - spark-network

  spark-worker2:
    image: henricasanova/ics632_spark-worker
    container_name: spark-worker2
    depends_on: 
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./:/home/spark
    networks:
      - spark-network

  spark-worker3:
    image: henricasanova/ics632_spark-worker
    container_name: spark-worker3
    depends_on: 
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - ./:/home/spark
    networks:
      - spark-network

  spark-worker4:
    image: henricasanova/ics632_spark-worker
    container_name: spark-worker4
    depends_on: 
      - spark-master
    ports:
      - "8084:8081"
    volumes:
      - ./:/home/spark
    networks:
      - spark-network

networks:
  spark-network:
    name: spark-network
    driver: bridge

